version: '3.8'

services:
  arangodb:
    image: arangodb:3.11
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    ports:
      - "${ARANGO_PORT}:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "arangosh", "--server.endpoint", "tcp://127.0.0.1:8529", "--server.password", "$${ARANGO_ROOT_PASSWORD}", "--javascript.execute-string", """db._databases()"""
      ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: coar-notify-inria-hal:latest
    depends_on:
      arangodb:
        condition: service_healthy
    environment:
      - ARANGO_HOST=${ARANGO_HOST}
      - ARANGO_PORT=${ARANGO_PORT}
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:5000"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "arangodb:${ARANGO_PORT}", "--", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app.app:app"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  arangodb_data:

# Usage:
# 1. Copy .env.example to .env and adjust as needed.
# 2. Run: docker compose up --build
# 3. Flask app: http://localhost:${FLASK_PORT}
# 4. ArangoDB UI: http://localhost:${ARANGO_PORT}
