version: '3.8'

services:
  arangodb:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD:-changeme}
      # ARANGO_NO_AUTH: '1'  # uncomment for local dev without password (NOT for production)
    ports:
      - "${ARANGO_PORT:-8529}:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped
    healthcheck:
      # Use arangosh and expand env inside the container
      test: ["CMD-SHELL", "arangosh --server.endpoint tcp://127.0.0.1:8529 --server.password \"$ARANGO_ROOT_PASSWORD\" --javascript.execute-string 'db._databases()'"]
      interval: 10s
      timeout: 5s
      retries: 12

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: coar-notify-inria-hal:latest
    depends_on:
      arangodb:
        condition: service_healthy
    environment:
      # Inside the docker network ArangoDB is always on port 8529
      ARANGO_HOST: arangodb
      ARANGO_PORT: 8529
      ARANGO_USERNAME: root
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD:-changeme}
      FLASK_PORT: ${FLASK_PORT:-5000}
    ports:
      - "${FLASK_PORT:-5000}:5000"
    restart: unless-stopped
    # Wait for the internal ArangoDB port (8529) with separate host and port args
    command: ["wait-for-it", "--host=arangodb", "--port=8529", "--", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app.app:app"]
    healthcheck:
      # Avoid relying on curl/wget; use Python stdlib to probe the HTTP endpoint
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5000/', timeout=2)\""]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  arangodb_data:
  arangodb_apps:

# Usage:
# 1. Create a .env file (or export env vars) with at least ARANGO_ROOT_PASSWORD, ARANGO_PORT and FLASK_PORT if you want non-defaults.
#    Example defaults are used if not provided: ARANGO_PORT=8529, FLASK_PORT=5000
# 2. Run: docker compose up --build
# 3. Flask app: http://localhost:${FLASK_PORT:-5000}
# 4. ArangoDB UI: http://localhost:${ARANGO_PORT:-8529}
